### ISSUE TITLE
Running Tessel 1 today

### ISSUE THREAD

**Issue by wautersj** [tessel/t1-docs#83]
Is there a way to get my Tessel 1 up and running today?

I don't seem to be able to install the CLI, due to deprecations and missing projects.
I tried lowering the node and npm versions, but failed to resolve it. Is there a specific setup that I can follow to get it to install again?

<img width="1300" alt="screenshot 2018-10-24 at 21 17 10" src="https://user-images.githubusercontent.com/4070167/47455457-31003000-d7d2-11e8-91d3-5e701061e1ad.png">

**Comment by Frijol** [comment]
Hi! yes, I was just playing around with my T1 & did a reinstall of the `tessel` CLI– worked on Node 10.10.0. Does that work on your computer?

**Comment by Kcharle** [comment]
@Frijol 

Can confirm this is not currently working, tried with node 10.10.0 as well as 10.16.0 and the latest version of 8.

Output

```
npm WARN deprecated tough-cookie@0.12.1: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated natives@1.1.6: This module relies on Node.js's internals and will break at some point. Do not use it, and update to graceful-fs@4.x.
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

> tessel@0.3.23 postinstall /Users/kyle/Downloads/package
> tessel install-drivers || true; tessel trademark || true

sh: tessel: command not found
sh: tessel: command not found
npm notice created a lockfile as package-lock.json. You should commit this file.
added 24 packages from 13 contributors, removed 33 packages, updated 3 packages, moved 3 packages and audited 296 packages in 3.667s
found 52 vulnerabilities (8 low, 24 moderate, 17 high, 3 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
➜  package npm install -g http://s3.amazonaws.com/builds.tessel.io/cli/tessel-cli-current.tar.gz
/.nvm/versions/node/v10.16.0/bin/tessel -> /.nvm/versions/node/v10.16.0/lib/node_modules/tessel/bin/tessel.js

> usb@1.0.6 install /.nvm/versions/node/v10.16.0/lib/node_modules/tessel/node_modules/usb
> node-pre-gyp install --fallback-to-build

node-pre-gyp info it worked if it ends with ok
node-pre-gyp verb cli [ '/.nvm/versions/node/v10.16.0/bin/node',
node-pre-gyp verb cli   '/.nvm/versions/node/v10.16.0/lib/node_modules/tessel/node_modules/usb/node_modules/.bin/node-pre-gyp',
node-pre-gyp verb cli   'install',
node-pre-gyp verb cli   '--fallback-to-build' ]
node-pre-gyp info using node-pre-gyp@0.6.4
node-pre-gyp info using node@10.16.0 | darwin | x64
node-pre-gyp verb command install []
node-pre-gyp info check checked for "/.nvm/versions/node/v10.16.0/lib/node_modules/tessel/node_modules/usb/src/binding/usb_bindings.node" (not found)
node-pre-gyp http GET https://tessel-builds.s3-us-west-2.amazonaws.com/pre-gyp/usb/v1.0.6/usb_bindings-v1.0.6-node-v64-darwin-x64.tar.gz
node-pre-gyp ERR! UNCAUGHT EXCEPTION 
node-pre-gyp ERR! stack Error: Cannot find module 'internal/util/types'
node-pre-gyp ERR! stack     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
node-pre-gyp ERR! stack     at Function.Module._load (internal/modules/cjs/loader.js:562:25)
node-pre-gyp ERR! stack     at Module.require (internal/modules/cjs/loader.js:690:17)
node-pre-gyp ERR! stack     at require (internal/modules/cjs/helpers.js:25:18)
node-pre-gyp ERR! stack     at evalmachine.<anonymous>:44:31
node-pre-gyp ERR! stack     at Object.<anonymous> (/.nvm/versions/node/v10.16.0/lib/node_modules/tessel/node_modules/usb/node_modules/node-pre-gyp/node_modules/tar/node_modules/fstream/node_modules/graceful-fs/fs.js:11:1)
node-pre-gyp ERR! stack     at Module._compile (internal/modules/cjs/loader.js:776:30)
node-pre-gyp ERR! stack     at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
node-pre-gyp ERR! stack     at Module.load (internal/modules/cjs/loader.js:653:32)
node-pre-gyp ERR! stack     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
node-pre-gyp ERR! System Darwin 18.6.0
node-pre-gyp ERR! command "/.nvm/versions/node/v10.16.0/bin/node" "/.nvm/versions/node/v10.16.0/lib/node_modules/tessel/node_modules/usb/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /.nvm/versions/node/v10.16.0/lib/node_modules/tessel/node_modules/usb
node-pre-gyp ERR! node -v v10.16.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.4
node-pre-gyp ERR! This is a bug in `node-pre-gyp`.
node-pre-gyp ERR! Try to update node-pre-gyp and file an issue if it does not help:
node-pre-gyp ERR!     <https://github.com/mapbox/node-pre-gyp/issues>
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: tap@0.4.13 (node_modules/tessel/node_modules/tap):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Cannot read property 'type' of undefined
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: tape@2.12.3 (node_modules/tessel/node_modules/tape):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Cannot read property 'type' of undefined

npm ERR! code ELIFECYCLE
npm ERR! errno 7
npm ERR! usb@1.0.6 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 7
npm ERR! 
npm ERR! Failed at the usb@1.0.6 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by nicolaevladescu** [comment]
It would also help if we could know the exact version of nodejs that is supported (mostly) by `colony-lua`.

In https://github.com/tessel/t1-docs/blob/master/compatibility.md it just says to visit http://nodejs.org/api/, but that page obviously has the docs for the latest node.

**Comment by Frijol** [comment]
Good question. @tcr would be the best person to know that
